# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-category', 'title']},
        ),
        migrations.AddField(
            model_name='channel',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is favorite?'),
        ),
    ]
