# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20160110_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='channel',
            name='alternative_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.CharField(choices=[('Educational', 'Educational'), ('Entertainment', 'Entertainment'), ('Films', 'Films'), ('Kids', 'Kids'), ('Man', 'Man'), ('Music', 'Music'), ('News', 'News'), ('Other', 'Other'), ('Public', 'Public'), ('Regional', 'Regional'), ('Religion', 'Religion'), ('Sport', 'Sport'), ('Woman', 'Woman')], max_length=255),
        ),
    ]
